name: Update GitHub Trophy

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: ysr-yashveer
          token: ${{ secrets.GH_PAT }}
          file: profile/trophy.svg
          theme: tokyonight
          max-cols: 6
          max-rows: 1
          no-frame: true

      - name: Commit trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/trophy.svg

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update GitHub trophy"
            git push
          fi
